repos:
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: 7a279fad9f0f4b98c7f75fc966931bbd7034b0de
      hooks:
          - id: pretty-format-kotlin
            args: [--ktfmt, --ktfmt-style=google]
            files: ^.*\.kt$